databases:
  master:
    hostname: localhost
    port: 5432
    username: postgres
    password: Test1234
    database: social_network
  slaves:
    - hostname: localhost
      port: 6432
      username: postgres
      password: Test1234
      database: social_network
    - hostname: localhost
      port: 7432
      username: postgres
      password: Test1234
      database: social_network