databases:
  master:
    hostname: postgres_1
    port: 5432
    username: postgres
    password: Test1234
    database: social_network
  slaves:
    - hostname: postgres_2
      port: 6432
      username: postgres
      password: Test1234
      database: social_network
    - hostname: postgres_3
      port: 7432
      username: postgres
      password: Test1234
      database: social_network